/* --------------------------------------------------------------------
 *
 * The MIT License
 *
 * Copyright (C) 2024  Gary W. Lucas.

 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * ---------------------------------------------------------------------
 */


 //  About the nodeIndex array:
 //  Early versions of this code used a tree based structure with pointers to
 //  the child nodes for each branch node.  But testing indicated that the overhead
 //  for navigating the tree had a strong impact on performance.  As an alternate
 //  we use a nodeIndex array to represent the virtual structure for the Huffman code:
 //    1. Given a Huffman tree with nNode nodes (including branches and terminal nodes),
 //       allocate nodeIndex = int[2*nNode].  
 //    2. Each node is indicated by a pair of adjacent array entries.  So the ith node will
 //       be located at nodeIndex[i*2] and nodeIndex[i*2+1].
 //    3. For branch nodes,  nodeIndex[i*2] indicates the left-side child of the branch
 //       (the branch associated with bit value of 0) and node[index[i*2+1] the right
 //       (the branch associated with bit value of 1).
 //    4. For symbol (terminal) nodes, nodeIndex[i*2] is set to zero.  NodeIndex[i*2+1] is
 //       set to the value of the symbol (which may be any integer, including zero and negative values).
 //  
 //  About the quick-entry table:
 //  The quick-entry table provides us with a way of avoiding, or shortening, the traversal
 //  of the nodeIndex array.  As the code loops through the encoded symbols in the input bit stream,
 //  it extracts 8 bits at the top of the loop.  These bits give the code an index in the range
 //  0 to 255 for looking up an entry in the quick-entry table.  
 //     1. For symbols with an encoded bit length of 8 or less, the quick-entry table
 //        gives a value for the symbol.  
 //     2. For symbols with an encoded bit length greater than 8, the quick-entry table
 //        gives an index into the nodeIndex array.
 //     3. The quick-entry table tells the code how many bits to "consume" for the symbol
 //        (1 to 8) or the transition to nodeIndex (all 8).
 //  The quick-entry table is designed so that the bit-sequence for a symbol becomes the
 //  low-order bits for an array index into the table elements.  For example, a symbol 
 //  with bit sequence 110 (length 3) becomes array index of 6.  When the code extracts
 //  8 bits from the encoded bit-stream, the code does not actually know how many of those
 //  bits may apply to the symbol.  To resolve those 8 bits to either a symbol or a nodeIndex offset,
 //  a symbol with a short bit sequence would appear in the quick-entry table multiple times.
 //  This approach allows the quick-entry table to match any bit sequence that would include the
 //  symbol.  Using the example above, the code would store the data for a symbol at the
 //  following array indices:
 //        00000 110  (array index 6)
 //        00001 110  (array index 6+8 = 14)
 //        00010 110  (array index 6+8+8 = 22)
 //        00011 110  (array index 6+8+8+8 = 30)
 //  Note that the step increment for each entry is simply 2 raised to the power of the bit length.
 //  In this case, a bit length of 3 leads to a step increment of 8.
 //  
 //  

#include "GvrsFramework.h"

#include "GvrsCrossPlatform.h"
#include "GvrsError.h"
#include "GvrsCodec.h"
#include "GvrsCanonicalHuffman.h"





typedef struct {
	int bits;   // the bit sequence generated by the canonical Huffman algorithm
	int xbit;   // the bit sequence in order transmitted by the input-stream.
	int symbol;
	int bitsLength;
}CodeEntry;

typedef struct {
	int nUniqueSymbols;
	int firstCode[17];
	int maxCode[17];
	int firstSymbolIndex[17];
	int connellSymbol[I_N_SYMBOLS];

	// The "quick-entry" table elements
	int qLength[256]; // index for entry to the nodeIndex array
	int qSymbol[256];     // the symbol
	int qBits[256];   // number of bits for symbol
}CodeTable;


// a utility for freeing elements during an allocation failure.
// if everything is implemented correctly, this function should never be used.
static void* failFree(void* f) {
	if (f) {
		free(f);
	}
	return (void*)0;
}

static void* cleanFree(void* f) {
	if (f) {
		free(f);
	}
	return (void*)0;
}

static CodeTable* codeTableFree(CodeTable* table) {
	if (table) {
		free(table);
	}
	return (CodeTable*)0;
}



// Build a tree for the specified code lengths.  The last symbol is always the end-of-text symbol.
// So nCodeLengths is the number of unique possible symbols, including the end-of-text symbol.
// Some of the unique symbols may have zero length.
static CodeTable* buildCodeTableFromLengths(int* codeLengths, int nCodeLengths) {
	for (int i = 0; i < nCodeLengths; i++) {
		if (codeLengths[i] < 0 || codeLengths[i] >= 16) {
			return NULL;
		}
	}

	int n = nCodeLengths * 16;
	int* populated = calloc(n + 16, sizeof(int));
	if (!populated) {
		return (CodeTable*)0;
	}
	int nPopulated = 0;
	for (int i = 0; i < nCodeLengths; i++) {
		if (codeLengths[i] > 0) {
			int index = codeLengths[i] * nCodeLengths + i;
			populated[index] = 1;
			nPopulated++;
		}
	}

	CodeEntry* sortCodes = calloc((size_t)(nPopulated + 1), sizeof(CodeEntry));
	if (!sortCodes) {
		free(populated);
		return (CodeTable*)0;
	}

	// The popluated field is indexed by (codeLength,index) where index refers to
	// the codeLengths array.  The first nCodeLengths entries would refer to 
	// a code-length of zero.  These are never populated (they are just included in memory
	// to simplify arithmetic).  So, we can skip the first nCodeLengths block of populated flags. 
	int kSort = 0;
	for (int i = nCodeLengths; i < n; i++) {
		if (populated[i] != 0) {
			CodeEntry* entry = sortCodes + kSort;
			int index = i / nCodeLengths;
			int symbol = i - index * nCodeLengths;
			int length = codeLengths[symbol];
			entry->bitsLength = length;
			entry->symbol = symbol;
			kSort++;
			if (kSort == nPopulated) {
				break;
			}
		}
	}


	populated = cleanFree(populated);
	CodeTable* codeTable = calloc(1, sizeof(CodeTable));
	if (!codeTable) {
		return (CodeTable*)0;
	}

	codeTable->nUniqueSymbols = kSort;

	for (int i = 1; i < kSort; i++) {
		CodeEntry* p = sortCodes + (i - 1);  // prior sort code
		CodeEntry* s = sortCodes + i;
		s->bits = p->bits + 1;
		if (s->bitsLength > p->bitsLength) {
			s->bits = s->bits << (s->bitsLength - p->bitsLength);
		}
	}





	// Populate the elements related to Connell's algorithm ------------
	for (int i = 0; i < kSort; i++) {
		codeTable->connellSymbol[i] = sortCodes[i].symbol;
	}

	// Fill maxCode array with -1 for undefined lengths (will replace some of these later)
	for (int i = 0; i < 17; i++) {
		codeTable->maxCode[i] = -1;
	}


	for (int i = 0; i < kSort; i++) {
		int len = sortCodes[i].bitsLength;
		int q = sortCodes[i].bits;
		codeTable->firstCode[len] = q; // (int)codeBits[i].bits;
		codeTable->firstSymbolIndex[len] = i;
		n = 1;
		for (int j = i + 1; j < kSort; j++) {
			if (sortCodes[j].bitsLength == len) {
				n = j - i + 1;
			}
			else {
				break;
			}
		}
		codeTable->maxCode[len] = codeTable->firstCode[len] + n - 1;
		i += (n - 1);
	}

	int isQuickEntryRequested = 1;
	if (isQuickEntryRequested) {
		// populate the quick-entry elements ----------------
		// xmit variable is the bit code formatted in the same order
		// as appears in the BitInputStream class.  It is the mirror
		// image of the code-bits, except that we only capture the
		// first 8 bits max.
		for (int i = 0; i < kSort; i++) {
			int symbol = sortCodes[i].symbol;
			int len = sortCodes[i].bitsLength;
			int q = sortCodes[i].bits;
			n = len > 8 ? 8 : len;
			int xmit = (q >> (len - 1)) & 1;
			for (int j = 1; j < n; j++) {
				int bit = (q >> (len - 1 - j)) & 1;
				xmit |= (bit << j);
			}
			int jStep = 1 << n;
			for (int j = xmit; j < 256; j += jStep) {
				codeTable->qLength[j] = len;
				codeTable->qBits[j] = (q >> len - 8) & 0xff;
				codeTable->qSymbol[j] = symbol;
			}
		}
	}

	free(sortCodes);
	return codeTable;
}

static CodeTable* decodeCodeTable(GvrsCanonicalHuffmanAppInfo* hInfo, GvrsBitInput* input) {
	int pos0 = GvrsBitInputGetPosition(input);
	int codeLengths[CL_N_SYMBOLS];
	int k = 0;
	int prior = 0;
	int n;
	// loop on the number of symbols, including one for the end-of-text symbol
	while (k < CL_N_SYMBOLS) {
		int index = GvrsBitInputGetBits(input, 5);
		if (index <= CL_MAX_STANDARD) {
			prior = index;
			codeLengths[k++] = index;
		}
		else {
			switch (index) {
			case CL_REPEAT_PREV_2BITS:
				n = GvrsBitInputGetBits(input, 2) + 3;
				for (int i = 0; i < n; i++) {
					codeLengths[k++] = prior;
				}
				break;
			case CL_REPEAT_ZERO_3BITS:
				prior = 0;
				n = GvrsBitInputGetBits(input, 3) + 3;
				for (int i = 0; i < n; i++) {
					codeLengths[k++] = 0;
				}
				break;
			case CL_REPEAT_ZERO_7BITS:
				prior = 0;
				n = GvrsBitInputGetBits(input, 7) + 11;
				for (int i = 0; i < n; i++) {
					codeLengths[k++] = 0;
				}
				break;
			default:
				break;
			}
		}
	}

	int pos1 = GvrsBitInputGetPosition(input);
	hInfo->nBitsInPreamble += (pos1 - pos0);

	CodeTable* countTable = buildCodeTableFromLengths(codeLengths, CL_N_SYMBOLS);
	if (!countTable) {
		// the was an internal error or malloc failure
		return 0;
	}
	int* firstCode = countTable->firstCode;
	int* maxCode = countTable->maxCode;
	int* connellSymbol = countTable->connellSymbol;
	int* firstSymbolIndex = countTable->firstSymbolIndex;

	prior = 0;
	k = 0;
	int textLengths[I_N_SYMBOLS];
	while (k < I_N_SYMBOLS) {
		int codeVal = 0;
		int length = 0;
		int symbol = 0;
		int offset = 0;
		while (1) {
			int bit = GvrsBitInputGetBit(input);
			codeVal = (codeVal << 1) | bit;
			length++;
			if (codeVal <= maxCode[length]) {
				int offset = codeVal - firstCode[length];
				symbol = connellSymbol[firstSymbolIndex[length] + offset];
				break;
			}
		}

		if (symbol <= CL_MAX_STANDARD) {
			prior = symbol;
			textLengths[k++] = symbol;
		}
		else {
			switch (symbol) {
			case CL_REPEAT_PREV_2BITS:
				n = GvrsBitInputGetBits(input, 2) + 3;
				for (int i = 0; i < n; i++) {
					textLengths[k++] = prior;
				}
				break;
			case CL_REPEAT_ZERO_3BITS:
				prior = 0;
				n = GvrsBitInputGetBits(input, 3) + 3;
				for (int i = 0; i < n; i++) {
					textLengths[k++] = 0;
				}
				break;
			case CL_REPEAT_ZERO_7BITS:
				prior = 0;
				n = GvrsBitInputGetBits(input, 7) + 11;
				for (int i = 0; i < n; i++) {
					textLengths[k++] = 0;
				}
				break;
			default:
				break;
			}
		}
	}
	codeTableFree(countTable);

	return buildCodeTableFromLengths(textLengths, I_N_SYMBOLS);
}

int
GvrsCanonicalHuffmanReadInt(GvrsBitInput* input, int nSymbolsInText, int* text, GvrsCanonicalHuffmanAppInfo* appInfo) {
	GvrsCanonicalHuffmanAppInfo* hInfo;
	GvrsCanonicalHuffmanAppInfo hInfoLocal;
	if (appInfo) {
		hInfo = appInfo;
	}
	else {
		memset(&hInfoLocal, 0, sizeof(hInfoLocal));
		hInfo = &hInfoLocal;
	}

	int pos0 = GvrsBitInputGetPosition(input);

	hInfo->revision = GvrsBitInputGetBit(input);

	CodeTable* codeTable = decodeCodeTable(hInfo, input);
	if (!codeTable) {
		return GVRSERR_COMPRESSION_FAILURE;
	}
	int pos1 = GvrsBitInputGetPosition(input);
	hInfo->nBitsInCodeTable += (int64_t)(pos1 - pos0);


	int prior = 0;
	int iSymbol = 0;
	uint8_t* source = input->text;
	unsigned int scratch = input->scratch;
	int iSource = input->nBytesProcessed;
	int nBit = input->nBit;
	int nSource = input->nBytesInText;
	int n;
	unsigned int bit, bits;

	int* firstCode = codeTable->firstCode;
	int* maxCode = codeTable->maxCode;
	int* connellSymbol = codeTable->connellSymbol;
	int* firstSymbolIndex = codeTable->firstSymbolIndex;

	int* qLength = codeTable->qLength;
	int* qSymbol = codeTable->qSymbol;
	int* qBits = codeTable->qBits;

	int reserveByte3 = nSource - 2;
	while (iSymbol < nSymbolsInText) {

		if (nBit < 8) {
			// This is the only case where the loop might try to claim more bits
			// than stored in the bit source.  So we need to test.  If the logic
			// requests more than the available bits, it is okay to allow them
			// to go to zero.
			if (iSource < reserveByte3) {
				int temp = source[iSource] | (source[iSource + 1] << 8) | (source[iSource + 2] << 16);
				scratch |= (temp << nBit);
				nBit += 24;
				iSource += 3;
			}
			else {
				if (iSource < nSource) {
					scratch |= (source[iSource++] << nBit);
				}
				nBit += 8;
			}
		}

		int symbol = 0;
		int test = scratch & 0xff;
		int testLen = qLength[test];
		if (testLen <= 8) {
			symbol = qSymbol[test];
			scratch >>= testLen;
			nBit -= testLen;
		}
		else {
			// the quick-entry tables navigated the first 8 bits of the code,
			// but the code is longer than 8 bits. no jump ahead and then
			// access the source coding one bit at a time using Connell's algorithm.
			int codeVal = qBits[test];
			int length = 8;
			scratch >>= 8;
			nBit -= 8;
			while (1) {
				// bit = input.getBit() -------------------------
				if (nBit == 0) {
					scratch = source[iSource++] & 0xff;
					nBit = 8;
				}
				bit = scratch & 1;
				scratch >>= 1;
				nBit--;

				codeVal = (codeVal << 1) | bit;
				length++;
				if (codeVal <= maxCode[length]) {
					int offset = codeVal - firstCode[length];
					symbol = connellSymbol[firstSymbolIndex[length] + offset];
					break;
				}
			}
		}




		if (symbol < I_MAX_STANDARD) {
			symbol -= 128;
			text[iSymbol++] = symbol;
			prior = symbol;
		}
		else {
			switch (symbol) {
			case I_ESCAPE_2BITS:
				// bits = GvrsBitInputGetBits(input, 2);  ------------------------------
				if (nBit < 2) {
					scratch |= (source[iSource++] << nBit);
					nBit += 8;
				}
				bits = scratch & 0x03u;
				scratch >>= 2;
				nBit -= 2;

				// end of GetBits(2) --------------------------------------------
				prior = (prior << 2) | bits;
				text[iSymbol - 1] = prior;
				break;
			case I_ESCAPE_1BYTE:
				// bits = GvrsBitInputGetByte(input);  ---------------------------------
				if (nBit < 8) {
					scratch |= (source[iSource++] << nBit);
					nBit += 8;
				}
				bits = scratch & 0xffu;
				scratch >>= 8;
				nBit -= 8;
				// end of GetByte -------------------------------------------------
				prior = (prior << 8) | bits;
				text[iSymbol - 1] = prior;
				break;
			case I_NULL_DATA_CODE:
				prior = 0x80000000;
				text[iSymbol++] = prior;
				break;
			case I_END_OF_TEXT:
				// Early exit:  loop reached the end of text before accumulating the
				// number of symbols requested by the calling application.
				GvrsBitInputSetState(input, iSource, nBit, scratch);
				codeTableFree(codeTable);
				return iSymbol;
			default:
				return GVRSERR_BAD_COMPRESSION_FORMAT;
			}
		}
	}

	// There is a complication in the Gridfour format in that the escape symbols
	// modify the previous value.  So we don't really know that the input
	// is fully processed unless we reach an end-of-text or exhaust the input
	// bit stream. If the next symbol in the bit stream is an escape symbol,
	// we need to read it and process it. Also, if we get here, there might also
	// be an end-of-text in the bit stream. The end-of-text needs to be consumed
	// because there are cases where multiple, distinct integer sequences may be
	// concatenated into the bit stream (as in the case of the LSOP format).
	//    This design choice is based on keeping the above loop as efficient
	// as possible. But it has the consequence that the following code repeats
	// some of the logic that was given above.  Since it is only reading a small
	// number of symbols, less emphasis is given to efficiency
	//    In the loop below, we use the local variables (scratch, nBit, etc.) to
	// serve as a way of "peeking" at the content of the bit stream without
	// modifying it. Then we record the state variables only when they are
	// actually processed.  If the logic encounters one of the "ordinary", non-escape,
	// symbols, it will break the loop but will not "consume" that symbol.


	int finishLoop = 1;
	while (finishLoop) {
		GvrsBitInputSetState(input, iSource, nBit, scratch);
		int codeVal = 0;
		int length = 0;
		int symbol = 0;
		while (1) {
			// int bit = GvrsBitInputGetBit(input); -------------------------------
			if (nBit == 0) {
				if (iSource == nSource) {
					// all bits in the input stream have been consumed.
					// no further processing is required
					codeTableFree(codeTable);
					return iSymbol;
				}
				scratch = source[iSource++];
				nBit = 8;
			}
			bit = scratch & 0x01u;
			scratch >>= 1;
			nBit--;
			// end of GetBit() ----------------------------------------------------
			codeVal = (codeVal << 1) | bit;
			length++;
			if (codeVal <= maxCode[length]) {
				int offset = codeVal - firstCode[length];
				symbol = connellSymbol[firstSymbolIndex[length] + offset];
				break;
			}
		}


		switch (symbol) {
		case I_ESCAPE_2BITS:
			// bits = GvrsBitInputGetBits(input, 2);  ------------------------------
			if (nBit < 2) {
				scratch |= (source[iSource++] << nBit);
				nBit += 8;
			}
			bits = scratch & 0x03u;
			scratch >>= 2;
			nBit -= 2;

			// end of GetBits(2) --------------------------------------------
			prior = (prior << 2) | bits;
			text[iSymbol - 1] = prior;
			break;
		case I_ESCAPE_1BYTE:
			// bits = GvrsBitInputGetByte(input);  ---------------------------------
			if (nBit < 8) {
				scratch |= (source[iSource++] << nBit);
				nBit += 8;
			}
			bits = scratch & 0xffu;
			scratch >>= 8;
			nBit -= 8;
			// end of GetByte -------------------------------------------------
			prior = (prior << 8) | bits;
			text[iSymbol - 1] = prior;
			break;
		case I_END_OF_TEXT:
			// loop reached the end of text.  We will need to record the
			// state variables, but processing is otherwise complete.
			GvrsBitInputSetState(input, iSource, nBit, scratch);
			finishLoop = 0;
			break;
		default:
			// any remaining symbols would be part of a different encoding that
			// would be concatenated to this one...  just end the loop without
			// recording the state variables.
			finishLoop = 0;
		}
	}

	codeTableFree(codeTable);
	return iSymbol;

}
